apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: your.email.address
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
    
-------

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: drone-cert
  namespace: default
spec:
  secretName: mydrone-drone-tls
  issuerRef:
    name: letsencrypt 
    kind: ClusterIssuer
  commonName: drone.myhost.io # UPDATE
  dnsNames:
  - drone.myhost.io
  acme:
    config:
    - http01:
        ingress: drone-server #UPDATE name of your ingress
      domains:
      - drone.myhost.io #UPDATE
 
