apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: your.email.address
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
    
-------

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: drone-cert
  namespace: default
spec:
  secretName: drone-tls
  issuerRef:
    name: letsencrypt 
    kind: ClusterIssuer
  commonName: drone.mycorp.calm # UPDATE
  dnsNames:
  - drone.mycorp.calm
  acme:
    config:
    - http01:
        ingress: drone-ingress #UPDATE name of your ingress
      domains:
      - drone.mycorp.calm #UPDATE
 
